manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cfergeau
      url-base: https://github.com/cfergeau
    - name: NuclearSquid
      url-base: https://github.com/Nuclear-Squid
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-config-totem
      remote: cfergeau
      revision: zmk-module
    - name: zmk-keyboard-quacken
      remote: NuclearSquid
      revision: main
  self:
    path: config
